// File generated by FlutterFire CLI or custom setup.
// Replace with your actual Firebase project credentials or run `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux Firebase options not configured.');
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFg8UjRLo2HDs5AHHwrtAUlbZYC_p346Y',
    appId: '1:277234184290:web:70dc956a5b7274dfafa13b',
    messagingSenderId: '277234184290',
    projectId: 'kini-chat',
    authDomain: 'kini-chat.firebaseapp.com',
    storageBucket: 'kini-chat.firebasestorage.app',
    measurementId: 'G-H739J1244Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTLF9OQw_-TlHvS3TMu3jw03B8QUlHSbo',
    appId: '1:277234184290:android:55e53c491764e690afa13b',
    messagingSenderId: '277234184290',
    projectId: 'kini-chat',
    storageBucket: 'kini-chat.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9QDUV6V3qR_GUJvDYthQHxckhSnEWRxo',
    appId: '1:277234184290:ios:a5f77d209eb5c0d4afa13b',
    messagingSenderId: '277234184290',
    projectId: 'kini-chat',
    storageBucket: 'kini-chat.firebasestorage.app',
    iosBundleId: 'com.example.crossChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFg8UjRLo2HDs5AHHwrtAUlbZYC_p346Y',
    appId: '1:277234184290:web:394e13c69cc906c6afa13b',
    messagingSenderId: '277234184290',
    projectId: 'kini-chat',
    authDomain: 'kini-chat.firebaseapp.com',
    storageBucket: 'kini-chat.firebasestorage.app',
    measurementId: 'G-13282R2NQK',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyMacosMock1234567890',
    appId: '1:1234567890:ios:mockappmacos',
    messagingSenderId: '1234567890',
    projectId: 'cross-chat-app-demo',
    storageBucket: 'cross-chat-app-demo.appspot.com',
    iosBundleId: 'com.example.crossChatApp',
  );
}
